// Code generated by goctl. DO NOT EDIT.
// Source: users.proto

package server

import (
	"context"

	"user/internal/logic"
	"user/internal/svc"
	"user/pb/users"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	users.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// -----------------------user-----------------------
func (s *UserServer) AddUser(ctx context.Context, in *users.AddUserReq) (*users.AddUserResp, error) {
	l := logic.NewAddUserLogic(ctx, s.svcCtx)
	return l.AddUser(in)
}

func (s *UserServer) TranAddUser(ctx context.Context, in *users.InviteUserReq) (*users.AddUserResp, error) {
	l := logic.NewTranAddUserLogic(ctx, s.svcCtx)
	return l.TranAddUser(in)
}

func (s *UserServer) TranDelUser(ctx context.Context, in *users.InviteUserReq) (*users.AddUserResp, error) {
	l := logic.NewTranDelUserLogic(ctx, s.svcCtx)
	return l.TranDelUser(in)
}

func (s *UserServer) UpdateUser(ctx context.Context, in *users.UpdateUserReq) (*users.UpdateUserResp, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserServer) DelUser(ctx context.Context, in *users.DelUserReq) (*users.DelUserResp, error) {
	l := logic.NewDelUserLogic(ctx, s.svcCtx)
	return l.DelUser(in)
}

func (s *UserServer) GetUserById(ctx context.Context, in *users.GetUserByIdReq) (*users.GetUserByIdResp, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *UserServer) GetUserByCode(ctx context.Context, in *users.GetUserByCodeReq) (*users.GetUserByIdResp, error) {
	l := logic.NewGetUserByCodeLogic(ctx, s.svcCtx)
	return l.GetUserByCode(in)
}

func (s *UserServer) SearchUser(ctx context.Context, in *users.SearchUserReq) (*users.SearchUserResp, error) {
	l := logic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}
