// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: scores.proto

package scores

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------score--------------------------------
type Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`         //id
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"` //userId
	Score  int64 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`   //score
}

func (x *Score) Reset() {
	*x = Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{0}
}

func (x *Score) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Score) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Score) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type AddScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` //userId
	Score  int64 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`   //score
}

func (x *AddScoreReq) Reset() {
	*x = AddScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoreReq) ProtoMessage() {}

func (x *AddScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoreReq.ProtoReflect.Descriptor instead.
func (*AddScoreReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{1}
}

func (x *AddScoreReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddScoreReq) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type AddScoreResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddScoreResp) Reset() {
	*x = AddScoreResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoreResp) ProtoMessage() {}

func (x *AddScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoreResp.ProtoReflect.Descriptor instead.
func (*AddScoreResp) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{2}
}

type UpdateScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`         //id
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"` //userId
	Score  int64 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`   //score
}

func (x *UpdateScoreReq) Reset() {
	*x = UpdateScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreReq) ProtoMessage() {}

func (x *UpdateScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreReq.ProtoReflect.Descriptor instead.
func (*UpdateScoreReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateScoreReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateScoreReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateScoreReq) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UpdateScoreResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateScoreResp) Reset() {
	*x = UpdateScoreResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreResp) ProtoMessage() {}

func (x *UpdateScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreResp.ProtoReflect.Descriptor instead.
func (*UpdateScoreResp) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{4}
}

type DelScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *DelScoreReq) Reset() {
	*x = DelScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelScoreReq) ProtoMessage() {}

func (x *DelScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelScoreReq.ProtoReflect.Descriptor instead.
func (*DelScoreReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{5}
}

func (x *DelScoreReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelScoreResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelScoreResp) Reset() {
	*x = DelScoreResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelScoreResp) ProtoMessage() {}

func (x *DelScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelScoreResp.ProtoReflect.Descriptor instead.
func (*DelScoreResp) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{6}
}

type GetScoreByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *GetScoreByIdReq) Reset() {
	*x = GetScoreByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoreByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreByIdReq) ProtoMessage() {}

func (x *GetScoreByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreByIdReq.ProtoReflect.Descriptor instead.
func (*GetScoreByIdReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{7}
}

func (x *GetScoreByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetScoreByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score *Score `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"` //score
}

func (x *GetScoreByIdResp) Reset() {
	*x = GetScoreByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoreByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreByIdResp) ProtoMessage() {}

func (x *GetScoreByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreByIdResp.ProtoReflect.Descriptor instead.
func (*GetScoreByIdResp) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{8}
}

func (x *GetScoreByIdResp) GetScore() *Score {
	if x != nil {
		return x.Score
	}
	return nil
}

type SearchScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page   int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`     //page
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   //limit
	Id     int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`         //id
	UserId int64 `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"` //userId
	Score  int64 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`   //score
}

func (x *SearchScoreReq) Reset() {
	*x = SearchScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchScoreReq) ProtoMessage() {}

func (x *SearchScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchScoreReq.ProtoReflect.Descriptor instead.
func (*SearchScoreReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{9}
}

func (x *SearchScoreReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchScoreReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchScoreReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchScoreReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchScoreReq) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchScoreResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score []*Score `protobuf:"bytes,1,rep,name=score,proto3" json:"score,omitempty"` //score
}

func (x *SearchScoreResp) Reset() {
	*x = SearchScoreResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchScoreResp) ProtoMessage() {}

func (x *SearchScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchScoreResp.ProtoReflect.Descriptor instead.
func (*SearchScoreResp) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{10}
}

func (x *SearchScoreResp) GetScore() []*Score {
	if x != nil {
		return x.Score
	}
	return nil
}

var File_scores_proto protoreflect.FileDescriptor

var file_scores_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x3b, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x41, 0x64,
	0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4e, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1d, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c,
	0x44, 0x65, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x37, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x78, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x22, 0x36, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0xae, 0x03, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x13, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x41,
	0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x54,
	0x72, 0x61, 0x6e, 0x49, 0x6e, 0x63, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x13, 0x2e, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x44, 0x65,
	0x63, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x13, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e,
	0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x16, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x35, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x13, 0x2e,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x2e, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scores_proto_rawDescOnce sync.Once
	file_scores_proto_rawDescData = file_scores_proto_rawDesc
)

func file_scores_proto_rawDescGZIP() []byte {
	file_scores_proto_rawDescOnce.Do(func() {
		file_scores_proto_rawDescData = protoimpl.X.CompressGZIP(file_scores_proto_rawDescData)
	})
	return file_scores_proto_rawDescData
}

var file_scores_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_scores_proto_goTypes = []interface{}{
	(*Score)(nil),            // 0: scores.Score
	(*AddScoreReq)(nil),      // 1: scores.AddScoreReq
	(*AddScoreResp)(nil),     // 2: scores.AddScoreResp
	(*UpdateScoreReq)(nil),   // 3: scores.UpdateScoreReq
	(*UpdateScoreResp)(nil),  // 4: scores.UpdateScoreResp
	(*DelScoreReq)(nil),      // 5: scores.DelScoreReq
	(*DelScoreResp)(nil),     // 6: scores.DelScoreResp
	(*GetScoreByIdReq)(nil),  // 7: scores.GetScoreByIdReq
	(*GetScoreByIdResp)(nil), // 8: scores.GetScoreByIdResp
	(*SearchScoreReq)(nil),   // 9: scores.SearchScoreReq
	(*SearchScoreResp)(nil),  // 10: scores.SearchScoreResp
}
var file_scores_proto_depIdxs = []int32{
	0,  // 0: scores.GetScoreByIdResp.score:type_name -> scores.Score
	0,  // 1: scores.SearchScoreResp.score:type_name -> scores.Score
	1,  // 2: scores.score.AddScore:input_type -> scores.AddScoreReq
	1,  // 3: scores.score.TranIncScore:input_type -> scores.AddScoreReq
	1,  // 4: scores.score.TranDecScore:input_type -> scores.AddScoreReq
	3,  // 5: scores.score.UpdateScore:input_type -> scores.UpdateScoreReq
	5,  // 6: scores.score.DelScore:input_type -> scores.DelScoreReq
	7,  // 7: scores.score.GetScoreById:input_type -> scores.GetScoreByIdReq
	9,  // 8: scores.score.SearchScore:input_type -> scores.SearchScoreReq
	2,  // 9: scores.score.AddScore:output_type -> scores.AddScoreResp
	2,  // 10: scores.score.TranIncScore:output_type -> scores.AddScoreResp
	2,  // 11: scores.score.TranDecScore:output_type -> scores.AddScoreResp
	4,  // 12: scores.score.UpdateScore:output_type -> scores.UpdateScoreResp
	6,  // 13: scores.score.DelScore:output_type -> scores.DelScoreResp
	8,  // 14: scores.score.GetScoreById:output_type -> scores.GetScoreByIdResp
	10, // 15: scores.score.SearchScore:output_type -> scores.SearchScoreResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_scores_proto_init() }
func file_scores_proto_init() {
	if File_scores_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scores_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScoreResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateScoreResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelScoreResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoreByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoreByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchScoreResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scores_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scores_proto_goTypes,
		DependencyIndexes: file_scores_proto_depIdxs,
		MessageInfos:      file_scores_proto_msgTypes,
	}.Build()
	File_scores_proto = out.File
	file_scores_proto_rawDesc = nil
	file_scores_proto_goTypes = nil
	file_scores_proto_depIdxs = nil
}
